addons:
  ssh_known_hosts: $IP

before_install:
  - openssl aes-256-cbc -K $encrypted_33637a474f6c_key -iv $encrypted_33637a474f6c_iv -in pshift.enc -out ~/.ssh/pshift -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/pshift
  - ssh-add ~/.ssh/pshift

script:
  - chmod +x ./deploy.sh
  - ./deploy.sh

notifications:
  email:
    on_failure: change

cache:
  directories:
    - ~/.ssh
