version: '3'

services:
  service:
    build: ./backend
    ports:
      - 3001:3001
  www:
    build: ./www
    ports:
      - 80:80
    depends_on:
      - service
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/document/swagger.yaml
    volumes:
      - ./document:/document
