version: '3'

services:
  service:
    build: ./backend
    ports:
      - 3001:3000
  www:
    build: ./www
    ports:
      - 3000:80
    depends_on:
      - service
  curl:
    image: byrnedo/alpine-curl
    command: curl http://service:3000/api/gigs
    depends_on:
      - service

